name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --no-progress --prefer-dist

      - name: Verify PHPUnit Installation
        run: ls vendor/bin/phpunit

      - name: Generate application key
        run: php artisan key:generate

      - name: Adjust directory permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Create SQLite database file
        run: touch database/database.sqlite

      - name: Run PHPUnit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          php artisan migrate --env=testing --database=sqlite
          vendor/bin/phpunit
